services:
  db:
    image: postgres:17
    env_file:
      - ./devops/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      retries: 5

  migrate:
    image: farm-rest-rpg-migrate
    build:
      context: ./db
      dockerfile: Dockerfile.migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./devops/.env
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/.migrated"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  db_seed:
    image: farm-rest-rpg-db-seed
    build:
      context: ./backend
      dockerfile: Dockerfile.db_seed
    depends_on:
      migrate:
        condition: service_healthy
    env_file:
      - ./devops/.env
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/.seeded"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: farm-rest-rpg-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./devops/.env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_healthy
      db_seed:
        condition: service_healthy

  frontend:
    image: farm-rest-rpg-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
