# backend/Dockerfile.db_seed
FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o seed ./cmd/seed

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache libc6-compat

COPY --from=builder /app/seed .
RUN mkdir -p /tmp

ENTRYPOINT ["sh", "-c", "\
    ./seed && \
    touch /tmp/.seeded && \
    echo 'Seeding Completed'; \
    sleep 300 \
"]
