# Dockerfile.migrate
FROM golang:1.24

# install goose once at build time
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# copy the migrations into the image
COPY . /db

WORKDIR /db

# default command can be overriden in compose
ENTRYPOINT ["bash", "-c", "\
    goose up && \
    touch /tmp/.migrated && \
    echo 'Migration Completed'; \
    sleep 60 \
"]
