# Dockerfile.migrate
FROM golang:1.24

# install goose once at build time
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# copy the migrations into the image
COPY . /db

WORKDIR /db

# default command can be overriden in compose if you like
ENTRYPOINT ["bash", "-c", "goose up && echo 'Migration Completed' > /tmp/.migrated && sleep 20"]
