// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventory.sql

package repository

import (
	"context"
)

const addInventoryItem = `-- name: AddInventoryItem :one
INSERT INTO "inventory" (user_id, item_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_id) DO NOTHING
RETURNING id, user_id, item_id, quantity
`

type AddInventoryItemParams struct {
	UserID   int32
	ItemID   int32
	Quantity int32
}

func (q *Queries) AddInventoryItem(ctx context.Context, arg AddInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, addInventoryItem, arg.UserID, arg.ItemID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
	)
	return i, err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, user_id, item_id, quantity
FROM "inventory"
WHERE user_id = $1 AND item_id = $2
`

type GetInventoryItemParams struct {
	UserID int32
	ItemID int32
}

func (q *Queries) GetInventoryItem(ctx context.Context, arg GetInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, arg.UserID, arg.ItemID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
	)
	return i, err
}

const hasItemQuantity = `-- name: HasItemQuantity :one
SELECT quantity >= $3 AS has_enough
FROM "inventory"
WHERE user_id = $1 AND item_id = $2
`

type HasItemQuantityParams struct {
	UserID   int32
	ItemID   int32
	Quantity int32
}

func (q *Queries) HasItemQuantity(ctx context.Context, arg HasItemQuantityParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasItemQuantity, arg.UserID, arg.ItemID, arg.Quantity)
	var has_enough bool
	err := row.Scan(&has_enough)
	return has_enough, err
}

const listInventoryItems = `-- name: ListInventoryItems :many
SELECT id, user_id, item_id, quantity
FROM "inventory"
WHERE user_id = $1
`

func (q *Queries) ListInventoryItems(ctx context.Context, userID int32) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventoryItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInventoryItem = `-- name: RemoveInventoryItem :exec
DELETE FROM "inventory"
WHERE item_id = $2 AND user_id = $1
`

type RemoveInventoryItemParams struct {
	UserID int32
	ItemID int32
}

func (q *Queries) RemoveInventoryItem(ctx context.Context, arg RemoveInventoryItemParams) error {
	_, err := q.db.Exec(ctx, removeInventoryItem, arg.UserID, arg.ItemID)
	return err
}

const setInventoryItemQuantity = `-- name: SetInventoryItemQuantity :one
INSERT INTO "inventory" (user_id, item_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_id) DO UPDATE
SET quantity = EXCLUDED.quantity
RETURNING id, user_id, item_id, quantity
`

type SetInventoryItemQuantityParams struct {
	UserID   int32
	ItemID   int32
	Quantity int32
}

func (q *Queries) SetInventoryItemQuantity(ctx context.Context, arg SetInventoryItemQuantityParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, setInventoryItemQuantity, arg.UserID, arg.ItemID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
	)
	return i, err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE "inventory"
SET user_id = $2,
    item_id = $3,
    quantity = $4
WHERE id = $1
RETURNING id, user_id, item_id, quantity
`

type UpdateInventoryItemParams struct {
	ID       int32
	UserID   int32
	ItemID   int32
	Quantity int32
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.ID,
		arg.UserID,
		arg.ItemID,
		arg.Quantity,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
	)
	return i, err
}

const upsertInventoryItem = `-- name: UpsertInventoryItem :one
INSERT INTO inventory (user_id, item_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_id) DO UPDATE
SET quantity = inventory.quantity + EXCLUDED.quantity
RETURNING id, user_id, item_id, quantity
`

type UpsertInventoryItemParams struct {
	UserID   int32
	ItemID   int32
	Quantity int32
}

func (q *Queries) UpsertInventoryItem(ctx context.Context, arg UpsertInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, upsertInventoryItem, arg.UserID, arg.ItemID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.Quantity,
	)
	return i, err
}
