// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Crop struct {
	ID                int32
	Name              string
	GrowthTimeSeconds int32
	YieldAmount       int32
}

type Farm struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Inventory struct {
	ID       int32
	UserID   int32
	ItemID   int32
	Quantity int32
}

type Item struct {
	ID         int32
	Name       string
	Tool       string
	EffectJson []byte
}

type Plot struct {
	ID        int32
	FarmID    int32
	CropID    *int32
	PlantedAt time.Time
	HarvestAt time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    int32
	Token     string
	ExpiresAt time.Time
	Revoked   *bool
	CreatedAt *time.Time
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
