// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int32
	Username     string
	Email        sql.NullString
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
